---
## Ansible 2.9.6
## Author: Alfred Valderrama
## alfred98valderrama@gmail.com

- include_tasks: variables.yml
- include_tasks: CentOS-8.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
  ignore_errors: '{{ ansible_check_mode }}'

- include_tasks: CentOS-7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  ignore_errors: '{{ ansible_check_mode }}'

- include_tasks: Debian-10.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"
  ignore_errors: '{{ ansible_check_mode }}'

- include_tasks: Debian-9.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"
  ignore_errors: '{{ ansible_check_mode }}'

- include_tasks: Ubuntu-20.04.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20"
  ignore_errors: '{{ ansible_check_mode }}'

- include_tasks: Ubuntu-18.04.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
  ignore_errors: '{{ ansible_check_mode }}'
